"""03b Task 5: choose the ML models of the learning curve by INNER-CV WAPE (never by test).

Reads the main arm's timing.csv (one row per tuned model and seed, column `cv_wape` = pooled out-of-fold WAPE on the
household-disjoint inner substations, kW scale, see train.tune_grouped_cv). For every (mode, family) the spec
(model, anchor, feature set, transform) with the lowest MEDIAN cv_wape over the seeds is selected. Families:
linear (Linear, Ridge, Lasso, ElasticNet, PLS), kernel (SVR), tree (XGBoost, XGBoost_mono); residual models exist for
linear and tree only. Writes results/iter03b_fair_test/lc_selection.csv and configs/iter03b_lc.yaml (the learning-curve
arm: all physics rows plus the selected specs, on the main arm's first `--seeds` seeds; its own main-part grid is one cheap
physics row, `slope_only`, so the arm's metrics.csv is non-empty).

    python scripts/paperb/select_lc_specs.py --timing results/iter03b_fair_test/arm_main/timing.csv --seeds 10
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import pandas as pd  # noqa: E402
import yaml  # noqa: E402

from paperb import ROOT  # noqa: E402

FAMILY = {"Linear": "linear", "Ridge": "linear", "Lasso": "linear", "ElasticNet": "linear", "PLS": "linear",
          "SVR": "kernel", "XGBoost": "tree", "XGBoost_mono": "tree"}
PHYSICS_SPECS = ["paperA_sh_mh", "paperA_sh_mh_station", "paperA_cal", "paperA_corr", "paperA_corr_all", "paperA_corr_cal",
                 "slope_only", "slope_base", "calibrated_delta", "hdh"]
ANCHOR_ONLY = [f"anchor_only_{m}|{a}|-|direct|none" for m in ("Linear", "XGBoost") for a in ("size", "peak", "size+peak")]


def select(timing):
    t = timing[timing["cv_wape"].notna() & timing["method"].isin(FAMILY)].copy()
    t["family"] = t["method"].map(FAMILY)
    keys = ["mode", "family", "method", "anchor", "feature_set", "target_transform"]
    g = t.groupby(keys)["cv_wape"].agg(["median", "count"]).reset_index().rename(columns={"median": "cv_wape_median", "count": "n_seeds"})
    g = g[g["n_seeds"] >= 0.8 * g["n_seeds"].max()]                     # a spec that failed on many seeds is not eligible
    best = g.loc[g.groupby(["mode", "family"])["cv_wape_median"].idxmin()]
    return g.sort_values(["mode", "family", "cv_wape_median"]), best


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--timing", required=True)
    ap.add_argument("--seeds", type=int, default=10)
    ap.add_argument("--base", default="configs/iter03b_main.yaml")
    ap.add_argument("--out", default="results/iter03b_fair_test/lc_selection.csv")
    ap.add_argument("--config-out", default="configs/iter03b_lc.yaml")
    a = ap.parse_args()
    ranked, best = select(pd.read_csv(ROOT / a.timing))
    (ROOT / a.out).parent.mkdir(parents=True, exist_ok=True)
    ranked.to_csv(ROOT / a.out, index=False)
    specs = [f"{r.method}|{r.anchor}|{r.feature_set}|{r.mode}|{r.target_transform if r.mode == 'direct' else 'log'}"
             for r in best.itertuples()]
    cfg = {"base": a.base, "exp_id": "iter03b_lc", "out_dir": "results/iter03b_fair_test/arm_lc", "pred_figures": False,
           "split": {"seeds": list(range(a.seeds))}, "models": [], "modes": ["direct"], "residual_models": [],
           "physics_baselines": ["slope_only"], "anchor_only_baselines": {"models": [], "features": []}, "targets": ["HP_Peak"],
           "paperA": {"estimators": []},
           "learning_curve": {"n": [16, 32, 48, "all"], "draws": 3, "feature_sets": sorted(set(best["feature_set"])),
                              "specs": [f"{p}|none|-|-|-" for p in PHYSICS_SPECS] + ANCHOR_ONLY + specs}}
    (ROOT / a.config_out).write_text("# GENERATED by scripts/paperb/select_lc_specs.py from the main arm's inner-CV WAPE (03b Task 5).\n"
                                     + yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
    print(best.to_string(index=False))
    print("learning-curve specs:", specs)
